### ISSUE TITLE
NameError: name 'srcdir' is not defined

### ISSUE THREAD

**Issue by roblehmann** [epigen/dea_seurat#8]
Hello,
thanks for the effort to turn the Seurat pipeline into a snakemake. 
The following line in the Snakefile gives me an error since the function srcdir is not defined:

SDIR = os.path.realpath(os.path.dirname(srcdir("Snakefile")))

Had to comment it out to get to to run.
cheers

**Comment by sreichl** [comment]
Hi Robert,
thanks for reporting, I will fix it with the next release!

Cheers, Stephan
